INSERT INTO owner (id_owner, dni, owner_name, owner_lastname, owner_cellphone ) VALUES
(1, '12345678', 'John', 'Doe', '3001234567'),
(2, '87654321', 'Jane', 'Smith', '3007654321');

INSERT INTO pet (id_pet, pet_name, species, race, color, owner_id) VALUES
(1, 'Max', 'Dog', 'Golden Retriever', 'Golden', 1),
(2, 'Bella', 'Cat', 'Siamese', 'White', 1),
(3, 'Charlie', 'Dog', 'Beagle', 'Brown', 2),
(4, 'Mono', 'Dog', 'Poodle', 'beige',2 )

